name: core
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dartz: ^0.10.1

  # Json Annotation.
  json_annotation: ^4.0.1

  # Api client.
  dio: ^4.0.0

  # Api Contract.
  retrofit: ^3.0.0

  # Equatability between objects.
  equatable: ^2.0.0

  # Local database.
  hive: ^2.2.2
  hive_flutter: ^1.1.0

  # Package information.
  package_info_plus: ^1.4.2

  # Dio interceptor.
  dio_smart_retry: ^1.0.0
  dio_cache_interceptor: ^3.3.0

  # convenient code generator for get_it.
  injectable: ^1.5.3

  # A cleaner way to handle your environment variables.
  envied: ^0.3.0

  utils:
    path: ../utils

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Very good linter. please make linter happy :).
  very_good_analysis: ^3.0.1

  # Dependency Injection.
  injectable_generator: any

  # Runner.
  build_runner: ^2.3.2

  # Po
  freezed: ^2.1.0+1

  # Generator for json annotation.
  json_serializable: ^6.3.1

  # Generator for retrofit.
  retrofit_generator: ^4.0.3+1

  # Generator for envied.
  envied_generator: ^0.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
